get:
  description: Get locations matching parameters
  queryParameters:
    deviceId:
      description: Device id used as filter
      type: number
      required: false
    exactTime:
      description: Exact time used as filter
      type: string
      required: false
    startTime:
      description: Start time used as filter
      type: string
      required: false
    endTime:
      description: End time used as filter
      type: string
      required: false
  responses:
    200:
      description: Locations succesfully found
      body:
        application/vnd.collection+json:
          type: Location
          example: !include ../responses/location-response.json
    400:
      description: Request contains errors, e.g. invalid parameters
      body:
        application/vnd.collection+json:
          example: {
            "collection": {
              "version": "1.0",
              "href" : "http://localhost:8080/api/location",
              "error": {
                "title": "Parameter validation error",
                "code": "1001",
                "message": "deviceId must be a number"
              }
            }
          }
    404:
      description: No locations found matching given parameters
      body:
        application/vnd.collection+json:
          example: {
            "collection": {
              "version": "1.0",
              "href" : "http://localhost:8080/api/location",
              "error": {
                "title": "No items found",
                "code": "1002",
                "message": "No items found with given parameters"
              }
            }
          }
    500:
      description: Internal errors occured, e.g. unable to connect to database. Technical descriptions are not leaked to client.
      body:
        application/vnd.collection+json:
          example: {
            "collection": {
              "version": "1.0",
              "href" : "http://localhost:8080/api/location",
              "error": {
                "title": "Internal error",
                "code": "1003",
                "message": "Server encountered internal error"
              }
            }
          }
post:
  description: Add location with given parameters
  headers:
    x-authentication-key:
      description: Device's authentication key. Required if id is not present in request parameters
      required: false
  body:
    application/json:
      properties:
        deviceId:
          description: Device id. Required if authenticationKey is not present in headers
          type: number
        coordinates:
          description: Coordinates of location
          type: string
        time:
          description: Time of location update. Current time is used if not defined.
          type: string
          required: false
  responses:
    201:
      description: Location succesfully added. Returns inserted location
      body:
        application/vnd.collection+json:
          type: Location
          example: !include ../responses/location-response.json
    400:
      description: Request contains errors, e.g. invalid parameters
      body:
        application/vnd.collection+json:
          example: {
            "collection": {
              "version": "1.0",
              "href" : "http://localhost:8080/api/location",
              "error": {
                "title": "Parameter validation error",
                "code": "1001",
                "message": "deviceId must be a number"
              }
            }
          }
    500:
      description: Internal errors occured, e.g. unable to connect to database. Technical descriptions are not leaked to client.
      body:
        application/vnd.collection+json:
          example: {
            "collection": {
              "version": "1.0",
              "href" : "http://localhost:8080/api/location",
              "error": {
                "title": "Internal error",
                "code": "1003",
                "message": "Server encountered internal error"
              }
            }
          }
delete:
  description: Delete locations matching parameters
  queryParameters:
    deviceId:
      description: Device id used as filter. Required if other request parameters are not present.
      type: number
      required: false
    exactTime:
      description: Exact time used as filter. Required if other request parameters are not present.
      type: string
      required: false
    startTime:
      description: Start time used as filter. Required if other request parameters are not present.
      type: string
      required: false
    endTime:
      description: End time used as filter. Required if other request parameters are not present.
      type: string
      required: false
  responses:
    204:
      description: Locations successfully removed
    400:
      description: Request contains errors, e.g. invalid parameters
      body:
        application/vnd.collection+json:
          example: {
            "collection": {
              "version": "1.0",
              "href" : "http://localhost:8080/api/location",
              "error": {
                "title": "Parameter validation error",
                "code": "1001",
                "message": "deviceId must be a number"
              }
            }
          }
    500:
      description: Internal errors occured, e.g. unable to connect to database. Technical descriptions are not leaked to client.
      body:
        application/vnd.collection+json:
          example: {
            "collection": {
              "version": "1.0",
              "href" : "http://localhost:8080/api/location",
              "error": {
                "title": "Internal error",
                "code": "1003",
                "message": "Server encountered internal error"
              }
            }
          }