description: Remove device group matching parameters
queryParameters:
  id:
    description: Device group id used as filter. Required if other request parameters are not present.
    type: number
    required: false
  name:
    description: Device group name used as filter. Required if other request parameters are not present.
    required: false
    type: string
    maxLength: 50
    pattern: "[A-Za-z0-9_ .,-]{1,50}"
responses:
  204:
    description: Device group successfully removed
  400:
    description: Request contains errors, e.g. invalid parameters
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/device-groups",
            "error": {
              "title": "Parameter validation error",
              "code": "1001",
              "message": "Name must pass regexp: [A-Za-z0-9_ .,-]{1,50}"
            }
          }
        }
  404:
    description: Device group matching parameters not found
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/device-groups",
            "error": {
              "title": "No items found",
              "code": "1002",
              "message": "No items found with given parameters"
            }
          }
        }
  500:
    description: Internal errors occured.
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/device-groups",
            "error": {
              "title": "Internal error",
              "code": "1003",
              "message": "Server encountered internal error"
            }
          }