description: Delete measurements matching parameters
queryParameters:
  deviceId:
    description: Device id used as filter. Required if other request parameters are not present.
    type: number
    required: false
  exactTime:
    description: Exact time used as filter. Required if other request parameters are not present.
    type: string
    required: false
  startTime:
    description: Start time used as filter. Required if other request parameters are not present.
    type: string
    required: false
  endTime:
    description: End time used as filter. Required if other request parameters are not present.
    type: string
    required: false
responses:
  204:
    description: Measurements successfully removed
  400:
    description: Request contains errors, e.g. invalid parameters
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/measurements",
            "error": {
              "title": "Parameter validation error",
              "code": "1001",
              "message": "deviceId must be a number"
            }
          }
        }
  500:
    description: Internal errors occured, e.g. unable to connect to database.
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/measurements",
            "error": {
              "title": "Internal error",
              "code": "1003",
              "message": "Server encountered internal error"
            }
          }
        }