description: Add new device group with given parameters
body:
  application/json:
    properties:
      name:
        description: Device group name
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_ .,-]{1,50}"
      description:
        description: Device group description
        type: string
        maxLength: 100
        pattern: "[A-Za-z0-9_ .,-]{1,100}"
responses:
  201:
    description: Device group succesfully added. Returns inserted device group including generated id
    body:
      application/vnd.collection+json:
        type: DeviceGroup
        example: !include ../../responses/device-group-response.json
  400:
    description: Request contains errors, e.g. invalid parameters
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/device-groups",
            "error": {
              "title": "Parameter validation error",
              "code": "1001",
              "message": "Name must pass regexp: [A-Za-z0-9_ .,-]{1,50}"
            }
          }
        }
  409:
    description: Device group name already used for another device group
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/device-groups",
            "error": {
              "title": "Parameter conflict",
              "code": "1004",
              "message": "Parameter must be unique: name"
            }
          }
        }
  500:
    description: Internal errors occured, e.g. unable to connect to database.
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/device-groups",
            "error": {
              "title": "Internal error",
              "code": "1003",
              "message": "Server encountered internal error"
            }
          }
        }