description: Add new device icon with given parameters
queryParameters:
  name:
    description: Device icon name
    type: string
    maxLength: 25
    pattern: "^[A-Za-z0-9-_]{1,25}.(png)$"
body:
  multipart/form-data:
    type: file
    fileTypes: ['image/png']
responses:
  201:
    description: Device icon succesfully added. Returns inserted device icon attributes including generated id
    body:
      application/vnd.collection+json:
        type: DeviceIcon
        example: !include ../../responses/device-icon-response.json
  400:
    description: Request contains errors, e.g. invalid parameters
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/device-icons",
            "error": {
              "title": "Parameter validation error",
              "code": "1001",
              "message": "Name must pass regexp: ^[A-Za-z0-9-_]{1,25}.(png)$"
            }
          }
        }
  409:
    description: Device icon name already used for another device icon
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/device-icons",
            "error": {
              "title": "Parameter conflict",
              "code": "1004",
              "message": "Parameter must be unique: name"
            }
          }
        }
  500:
    description: Internal errors occured, e.g. unable to connect to database.
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/device-icons",
            "error": {
              "title": "Internal error",
              "code": "1003",
              "message": "Server encountered internal error"
            }
          }
        }