#%RAML 1.0
title: iot-device-manager
mediaType: application/json
baseUri: http://localhost:8080/rest
types:
  Device:
    type: object
    properties:
      id:
        description: Device id
        type: number
      name:
        description: Device name
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_ .,-]{1,50}"
      deviceTypeId:
        description: Device type id used as filter
        type: number
      deviceGroupId:
        description: Device group id used as filter
        type: number
      configurationId:
        description: Device configuration id used as filter
        type: number
      authenticationKey:
        description: Device authenticationKey used as filter. Required if name is not present.
        type: string
        minLength: 32
        maxLength: 32
  DeviceGroup:
    properties:
      id:
        description: Device group id
        type: number
      name:
        description: Device group name
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_ .,-]{1,50}"
      description:
        description: Device group description
        type: string
        maxLength: 100
        pattern: "[A-Za-z0-9_ .,-]{1,50}"
  DeviceIcon:
    properties:
    id:
      description: Device icon id
      type: number
    name:
      description: Device icon name
      type: string
      maxLength: 25
      pattern: "^[A-Za-z0-9-_]{1,25}.(png)$"
  errorResponse:
    type: object
    properties:
      errors: string[]
  devicesResponse:
    type: object
    properties:
      payload: Device[]
  deviceResponse:
    type: object
    properties:
      payload: Device
  deviceGroupsResponse:
    type: object
    properties:
      payload: DeviceGroup[]
  deviceGroupResponse:
    type: object
    properties:
      payload: DeviceGroup
  deviceIconResponse:
    type: file
    fileTypes: ['image/png']
  deviceIconAttributesResponse:
    type: object
    properties:
      payload: DeviceIcon

/device:
  get:
    description: Get devices matching parameters
    queryParameters:
      id:
        description: Device id used as filter
        type: number
        required: false
      name:
        description: Device name used as filter
        required: false
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_-]"
      deviceTypeId:
        description: Device type id used as filter
        type: number
        required: false
      deviceGroupId:
        description: Device group id used as filter
        type: number
        required: false
      configurationId:
        description: Device configuration id used as filter
        type: number
        required: false
      authenticationKey:
        description: Device authenticationKey used as filter. Required if name is not present.
        required: false
        type: string
        minLength: 32
        maxLength: 32
    responses:
      200:
        description: Devices succesfully found
        body:
          application/json:
            type: devicesResponse
            example: {
              payload: [
                {
                  id: 1,
                  name: "test-device",
                  deviceTypeId: 1,
                  deviceGroupId: 1,
                  configurationId: 1,
                  authenticationKey: "as7y7das0923jnawoij2n22jj2nekj2n"
                }
              ]
            }
      400:
        description: Request contains errors, e.g. invalid parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Invalid parameter: deviceTypeId with value: 'test'",
                "Invalid parameter length: name (max length 50)"
              ]
            }
      404:
        description: No devices found matching given parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Devices not found"
              ]
            }
      500:
        description: Internal errors occured, e.g. unable to connect to database. Technical descriptions are not leaked to client.
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Internal error"
              ]
            }
  post:
    description: Add new device with given parameters
    body:
      application/json:
        properties:
          name:
            type: string
            maxLength: 50
            pattern: "[A-Za-z0-9_-]"
          deviceTypeId:
            type: integer
            required: false
          deviceGroupId:
            type: integer
            required: false
          configurationId:
            type: integer
            required: false
    responses:
      201:
        description: Device succesfully added. Returns inserted device including generated id and authentication key
        body:
          application/json:
            type: deviceResponse
            example: {
              payload: {
                id: 1,
                name: "test-device",
                deviceTypeId: 1,
                deviceGroupId: 1,
                configurationId: 1,
                authenticationKey: "as7y7das0923jnawoij2n22jj2nekj2n"
              }
            }
      400:
        description: Request contains errors, e.g. invalid parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Invalid parameter: deviceTypeId with value: 'test'"
              ]
            }
      409:
        description: Device name already used for another device
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device name already in use. Name must be unique"
              ]
            }
      500:
        description: Internal errors occured, e.g. foreign key not matching. Technical descriptions are not leaked to client.
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Unable to add device. No configuration found with configurationId 1"
              ]
            }
  put:
    description: Update given attributes of device
    queryParameters:
      id:
        description: Device id used as filter. Required if other request parameters are not present.
        required: false
        type: number
      name:
        description: Device name used as filter. Required if other request parameters are not present.
        required: false
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_-]"
      authenticationKey:
        description: Device authenticationKey used as filter. Required if other request parameters are not present.
        required: false
        type: string
        minLength: 32
        maxLength: 32
    body:
      application/json:
        description: Attributes to update
        properties:
          name:
            required: false
            type: string
          deviceTypeId:
            required: false
            type: integer
          deviceGroupId:
            required: false
            type: integer
          configurationId:
            required: false
            type: integer
    responses:
      200:
        description: Device succesfully updated. Returns updated device
        body:
          application/json:
            type: deviceResponse
            example: {
              payload: {
                id: 1,
                name: "test-device",
                deviceTypeId: 1,
                deviceGroupId: 1,
                configurationId: 1,
                authenticationKey: "as7y7das0923jnawoij2n22jj2nekj2n"
              }
            }
      400:
        description: Request contains errors, e.g. invalid parameters, missing parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Invalid parameter: deviceTypeId with value: test"
              ]
            }
      404:
        description: Device matching parameters not found
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device with id 1 not found"
              ]
            }
      409:
        description: Device name already used for another device
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device name already in use. Name must be unique."
              ]
            }
      500:
        description: Internal errors occured, e.g. foreign key not matching. Technical descriptions are not leaked to client.
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Unable to update device. No configuration found with configurationId 1"
              ]
            }

  delete:
    description: Remove device matching parameters
    queryParameters:
      id:
        description: Device id used as filter. Required if other request parameters are not present.
        required: false
        type: number
      name:
        description: Device name used as filter. Required if other request parameters are not present.
        required: false
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_-]"
      authenticationKey:
        description: Device authenticationKey used as filter. Required if other request parameters are not present.
        required: false
        type: string
        minLength: 32
        maxLength: 32
    responses:
      204:
        description: Device successfully removed
      400:
        description: Request contains errors, e.g. invalid parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Invalid parameter: id with value: 'test'",
                "Invalid parameter length: name (max length 50)"
              ]
            }
      404:
        description: Device matching parameters not found
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device with id 1 not found"
              ]
            }
      500:
        description: Internal errors occured. Technical descriptions are not leaked to client.
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Internal error"
              ]
            }

/device_group:
  get:
    description: Get device groups matching parameters
    queryParameters: 
      id:
        description: Device group id used as filter
        type: number
        required: false
      name:
        description: Device group name used as filter
        required: false
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_-]"
    responses:
      200:
        description: Device groups succesfully found
        body:
          application/json:
            type: deviceGroupsResponse
            example: {
              payload: [
                {
                  id: 1,
                  name: "test-device-group",
                  description: "Description for test devices"
                }
              ]
            }
      400:
        description: Request contains errors, e.g. invalid parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Invalid parameter: id with value: 'test'",
                "Invalid parameter length: name (max length 50)"
              ]
            }
      404:
        description: No device groups found matching given parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device groups not found"
              ]
            }
      500:
        description: Internal errors occured, e.g. unable to connect to database. Technical descriptions are not leaked to client.
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Internal error"
              ]
            }
  post:
    description: Add new device group with given parameters
    body:
      application/json:
        properties:
          name:
            description: Device group name
            type: string
            maxLength: 50
            pattern: "[A-Za-z0-9_ .,-]{1,50}"
          description:
            description: Device group description
            type: string
            maxLength: 100
            pattern: "[A-Za-z0-9_ .,-]{1,50}"
    responses:
      201:
        description: Device group succesfully added. Returns inserted device group including generated id
        body:
          application/json:
            type: deviceGroupsResponse
            example: {
              payload: [
                {
                  id: 1,
                  name: "test-device-group",
                  description: "Description for test devices"
                }
              ]
            }
      400:
        description: Request contains errors, e.g. invalid parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Invalid parameter: id with value: 'test'",
                "Invalid parameter length: name (max length 50)"
              ]
            }
      409:
        description: Device group name already used for another device group
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device group name already in use. Name must be unique"
              ]
            }
      500:
        description: Internal errors occured, e.g. foreign key not matching. Technical descriptions are not leaked to client.
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Internal error"
              ]
            }
  put:
    description: Update given attributes of device group
    queryParameters:
      id:
        description: Device group id used as filter
        type: number
        required: false
      name:
        description: Device group name used as filter
        required: false
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_-]"
    body:
      application/json:
        description: Attributes to update
        properties:
          name:
            description: Device group name
            type: string
            maxLength: 50
            pattern: "[A-Za-z0-9_ .,-]{1,50}"
          description:
            description: Device group description
            type: string
            maxLength: 100
            pattern: "[A-Za-z0-9_ .,-]{1,50}"
    responses:
      200:
        description: Device group succesfully updated. Returns updated device group
        body:
          application/json:
            type: deviceGroupsResponse
            example: {
              payload: [
                {
                  id: 1,
                  name: "test-device-group",
                  description: "Description for test devices"
                }
              ]
            }
      400:
        description: Request contains errors, e.g. invalid parameters, missing parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Invalid parameter: id with value: test"
              ]
            }
      404:
        description: Device group matching parameters not found
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device group with id 1 not found"
              ]
            }
      409:
        description: Device group name already used for another device group
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device group name already in use. Name must be unique."
              ]
            }
      500:
        description: Internal errors occured. Technical descriptions are not leaked to client.
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Internal error"
              ]
            }
  delete:
    description: Remove device group matching parameters
    queryParameters:
      id:
        description: Device group id used as filter
        type: number
        required: false
      name:
        description: Device group name used as filter
        required: false
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_-]"
    responses:
      204:
        description: Device group successfully removed
      400:
        description: Request contains errors, e.g. invalid parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Invalid parameter: id with value: 'test'",
                "Invalid parameter length: name (max length 50)"
              ]
            }
      404:
        description: Device group matching parameters not found
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device group with id 1 not found"
              ]
            }
      500:
        description: Internal errors occured. Technical descriptions are not leaked to client.
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Internal error"
              ]
            }

/device_icon:
  get:
    description: Get device icon matching parameters
    queryParameters:
      id:
        description: Device icon id used as filter. Required if name not present
        type: number
        required: false
      name:
        description: Device icon name used as filter. Required if id not present
        required: false
        type: string
        maxLength: 25
        pattern: "^[A-Za-z0-9-_]{1,25}.(png)$"
    responses:
      200:
        description: Device icon succesfully found
        body:
          image/png:
            type: deviceIconResponse
      400:
        description: Request contains errors, e.g. invalid parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Missing request parameters: id or name required"
              ]
            }
      404:
        description: No device icon found matching given parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device icon not found"
              ]
            }
      500:
        description: Internal errors occured, e.g. unable to connect to database. Technical descriptions are not leaked to client.
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Internal error"
              ]
            }
  post:
    description: Add new device group with given parameters
    queryParameters:
      name:
        description: Device icon name
        type: string
        maxLength: 25
        pattern: "^[A-Za-z0-9-_]{1,25}.(png)$"
    body:
      multipart/form-data:
        type: deviceIconResponse
    responses:
      201:
        description: Device icon succesfully added. Returns inserted device icon attributes including generated id
        body:
          application/json:
            type: deviceIconAttributesResponse
            example: {
              payload: [
                {
                  id: 1,
                  name: "test-device-icon.png"
                }
              ]
            }
      400:
        description: Request contains errors, e.g. invalid parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Missing required parameter: name",
              ]
            }
      409:
        description: Device icon name already used for another device icon
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device icon name already in use. Name must be unique"
              ]
            }
      500:
        description: Internal errors occured. Technical descriptions are not leaked to client.
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Internal error"
              ]
            }
  put:
    description: Rename device icon
    queryParameters:
      id:
        description: Device icon id used as filter. Required if name not present
        type: number
        required: false
      name:
        description: Device icon name. Required if id not present
        type: string
        maxLength: 25
        pattern: "^[A-Za-z0-9-_]{1,25}.(png)$"
    body:
      application/json:
        description: Attributes to update
        properties:
          name:
            description: Device icon name
            type: string
            maxLength: 25
            pattern: "^[A-Za-z0-9-_]{1,25}.(png)$"
    responses:
      200:
        description: Device icon succesfully renamed. Returns updated attributes of device icon
        body:
          application/json:
            type: deviceIconAttributesResponse
            example: {
              payload: [
                {
                  id: 1,
                  name: "test-device-icon.png"
                }
              ]
            }
      400:
        description: Request contains errors, e.g. invalid parameters, missing parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Missing parameters: name or id required"
              ]
            }
      404:
        description: Device icon matching parameters not found
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device icon with id 1 not found"
              ]
            }
      409:
        description: Device icon name already used for another device icon
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device icon name already in use. Name must be unique."
              ]
            }
      500:
        description: Internal errors occured. Technical descriptions are not leaked to client.
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Internal error"
              ]
            }
  delete:
    description: Remove device icon matching parameters
    queryParameters:
      id:
        description: Device icon id used as filter. Required if name not present
        type: number
        required: false
      name:
        description: Device icon name. Required if id not present
        type: string
        maxLength: 25
        pattern: "^[A-Za-z0-9-_]{1,25}.(png)$"
    responses:
      204:
        description: Device icon successfully removed
      400:
        description: Request contains errors, e.g. invalid parameters, missing parameters
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Missing parameters: name or id required"
              ]
            }
      404:
        description: Device icon matching parameters not found
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Device icon with id 1 not found"
              ]
            }
      500:
        description: Internal errors occured. Technical descriptions are not leaked to client.
        body:
          application/json:
            type: errorResponse
            example: {
              errors: [
                "Internal error"
              ]
            }

/device_type:
  get:
  post:
  put:
  delete:

/location:
  get:
  put:
  delete:

/configuration:
  get:
  post:
  put:
  delete:
