#%RAML 1.0
title: iot-device-manager
mediaType: application/vnd.collection+json
baseUri: http://localhost:8080/api/v1
types:
  Device:
    type: object
    properties:
      id:
        description: Device id
        type: number
      name:
        description: Device name
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_ .,-]{1,50}"
      deviceTypeId:
        description: Device type id
        type: number
      deviceGroupId:
        description: Device group id
        type: number
      configurationId:
        description: Device configuration id
        type: number
      authenticationKey:
        description: Device authenticationKey
        type: string
        minLength: 32
        maxLength: 32
  DeviceGroup:
    type: object
    properties:
      id:
        description: Device group id
        type: number
      name:
        description: Device group name
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_ .,-]{1,50}"
      description:
        description: Device group description
        type: string
        maxLength: 100
        pattern: "[A-Za-z0-9_ .,-]{1,100}"
  DeviceIcon:
    type: object
    properties:
      id:
        description: Device icon id
        type: number
      name:
        description: Device icon name
        type: string
        maxLength: 25
        pattern: "^[A-Za-z0-9-_]{1,25}.(png)$"
  DeviceType:
    type: object
    properties:
      id:
        description: Device type id
        type: number
      name:
        description: Device type name
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_ .,-]{1,50}"
      deviceIconId:
        description: Device icon id
        type: number
  Location:
    type: object
    properties:
      deviceId:
        description: Device id
        type: number
      latitude:
        description: Latitude of coordinates
        type: number
      longitude:
        description: Longitude of coordinates
        type: number
      time:
        description: Time of location update
        type: string
  Measurement:
    type: object
    properties:
      deviceId:
        description: Device id
        type: number
      content:
        description: Content as JSON string
        type: string
      time:
        description: Time of the measurement
        type: string
  Configuration:
    type: object
    properties:
      id:
        description: Configuration id
        type: number
      name:
        description: Configuration's name
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_ .,-]{1,50}"
      description:
        description: Configuration's description
        type: string
        maxLength: 100
        pattern: "[A-Za-z0-9_ .,-]{1,100}"
      content:
        description: Configuration's content as JSON
        type: string

/devices:
  get: !include resources/get/device.raml
  post: !include resources/post/device.raml
  put: !include resources/put/device.raml
  delete: !include resources/delete/device.raml
  /{id}:
    uriParameters:
      id:
        type: number
        description: Device ID
    get: !include resources/get/device.raml
    put: !include resources/put/device.raml
    delete: !include resources/delete/device.raml
    /group:
      get: !include resources/get/device-group.raml
      post: !include resources/post/device-group.raml
      put: !include resources/put/device-group.raml
      delete: !include resources/delete/device-group.raml
    /type:
      get: !include resources/get/device-type.raml
      post: !include resources/post/device-type.raml
      put: !include resources/put/device-type.raml
      delete: !include resources/delete/device-type.raml
    /icon:
      get: !include resources/get/device-icon.raml
      put: !include resources/put/device-icon.raml
      delete: !include resources/delete/device-icon.raml
    /configuration:
      get: !include resources/get/configuration.raml
      post: !include resources/post/configuration.raml
      put: !include resources/put/configuration.raml
      delete: !include resources/delete/configuration.raml
    /measurements:
      get: !include resources/get/measurements.raml
      post: !include resources/post/measurements.raml
      delete: !include resources/delete/measurements.raml
    /locations:
      get: !include resources/get/location.raml
      post: !include resources/post/location.raml
      delete: !include resources/delete/location.raml
/device-groups:
  get: !include resources/get/device-group.raml
  post: !include resources/post/device-group.raml
  put: !include resources/put/device-group.raml
  delete: !include resources/delete/device-group.raml
  /{id}:
    uriParameters:
      id:
        type: number
        description: Device Group ID
    get: !include resources/get/device-group.raml
    put: !include resources/put/device-group.raml
    delete: !include resources/delete/device-group.raml
    /devices:
      get: !include resources/get/device.raml
      post: !include resources/post/device.raml
    /measurements:
      get: !include resources/get/measurements.raml
      delete: !include resources/delete/measurements.raml
    /locations:
      get: !include resources/get/location.raml
      delete: !include resources/delete/location.raml
/device-types:
  get: !include resources/get/device-type.raml
  post: !include resources/post/device-type.raml
  put: !include resources/put/device-type.raml
  delete: !include resources/delete/device-type.raml
  /{id}:
    uriParameters:
      id:
        type: number
        description: Device Type ID
    get: !include resources/get/device-type.raml
    put: !include resources/put/device-type.raml
    delete: !include resources/delete/device-type.raml
    /devices:
      get: !include resources/get/device.raml
      post: !include resources/post/device.raml
    /icon:
      get: !include resources/get/device-icon.raml
      post: !include resources/post/device-icon.raml
      put: !include resources/put/device-icon.raml
      delete: !include resources/delete/device-icon.raml
/device-icons:
  get: !include resources/get/device-icon.raml
  post: !include resources/post/device-icon.raml
  put: !include resources/put/device-icon.raml
  delete: !include resources/delete/device-icon.raml
  /{id}:
    uriParameters:
      id:
        type: number
        description: Device Icon ID
    get: !include resources/get/device-icon.raml
    put: !include resources/put/device-icon.raml
    delete: !include resources/delete/device-icon.raml
    /types:
      get: !include resources/get/device-type.raml
      post: !include resources/post/device-type.raml
      delete: !include resources/delete/device-type.raml
  /{icon-name}:
    uriParameters:
      icon-name:
        type: string
        description: Icon name
        example: example-icon.png
        maxLength: 25
        pattern: "^[A-Za-z0-9-_]{1,25}.(png)$"
    get: !include resources/get/device-icon-file.raml
/configurations:
  get: !include resources/get/configuration.raml
  post: !include resources/post/configuration.raml
  put: !include resources/put/configuration.raml
  delete: !include resources/delete/configuration.raml
  /{id}:
    uriParameters:
      id:
        type: number
        description: Configuration ID
    get: !include resources/get/configuration.raml
    put: !include resources/put/configuration.raml
    delete: !include resources/delete/configuration.raml
    /devices:
      get: !include resources/get/device.raml
      post: !include resources/post/device.raml
/locations:
  get: !include resources/get/location.raml
  post: !include resources/post/location.raml
  delete: !include resources/delete/location.raml
/measurements:
  get: !include resources/get/measurements.raml
  post: !include resources/post/measurements.raml
  delete: !include resources/delete/measurements.raml