source /home/create_databases.sql

USE iotdevicemanager;
source create_tables_triggers_user.sql
source procedures_configuration.sql
source procedures_device_group.sql
source procedures_device_icon.sql
source procedures_device.sql
source procedures_device_type.sql
source procedures_location.sql
source procedures_measurement.sql

USE testiotdevicemanager;
source create_tables_triggers_user.sql
source procedures_configuration.sql
source procedures_device_group.sql
source procedures_device_icon.sql
source procedures_device.sql
source procedures_device_type.sql
source procedures_location.sql
source procedures_measurement.sql