description: Update given attributes of configuration
queryParameters:
  id:
    description: Configuration id used as filter. Required if other request parameters are not present.
    type: number
    required: false
  name:
    description: Configuration name used as filter. Required if other request parameters are not present.
    required: false
    type: string
    maxLength: 50
    pattern: "[A-Za-z0-9_ .,-]{1,50}"
body:
  application/json:
    description: Attributes to update
    properties:
      name:
        description: Configuration's name
        type: string
        maxLength: 50
        pattern: "[A-Za-z0-9_ .,-]{1,50}"
      description:
        description: Configuration's description
        type: string
        maxLength: 100
        pattern: "[A-Za-z0-9_ .,-]{1,100}"
      jsonConfiguration:
        description: Configuration's content as JSON
        type: string
responses:
  200:
    description: Configuration succesfully updated. Returns updated configuration
    body:
      application/vnd.collection+json:
        type: Configuration
        example: !include ../../responses/configuration-response.json
  400:
    description: Request contains errors, e.g. invalid parameters
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/configurations",
            "error": {
              "title": "Parameter validation error",
              "code": "1001",
              "message": "id must be a number"
            }
          }
        }
  404:
    description: No configurations found matching given parameters
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/configurations",
            "error": {
              "title": "No items found",
              "code": "1002",
              "message": "No items found with given parameters"
            }
          }
        }
  409:
    description: Configuration name already used for another device type
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/configurations",
            "error": {
              "title": "Parameter conflict",
              "code": "1004",
              "message": "Parameter must be unique: name"
            }
          }
        }
  500:
    description: Internal errors occured, e.g. unable to connect to database.
    body:
      application/vnd.collection+json:
        example: {
          "collection": {
            "version": "1.0",
            "href" : "http://localhost:8080/api/v1/configurations",
            "error": {
              "title": "Internal error",
              "code": "1003",
              "message": "Server encountered internal error"
            }
          }
        }